import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar";

export const metadata: Metadata = {
  title: "coli-js",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <header className="text-xl font-bold leading-[4rem]">
          <Link href="/">coli-js</Link>
          <nav className="flex-1 space-x-8 text-center ">
            <Avatar>
              <AvatarImage src="https://avatars.githubusercontent.com/u/171585901?s=200&v=4" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <Link href="/">
              <button
                className=" rounded-lg bg-white  text-black shadow-md shadow-white duration-300 hover:mx-2 hover:scale-110 hover:delay-200"
                type="button"
              >
                <p className="px-5 py-2 text-base">Categoria 1</p>
              </button>
            </Link>
            <Link href="/">
              <button
                className="rounded-lg bg-white  text-black shadow-md shadow-white duration-300 hover:mx-2 hover:scale-110 hover:delay-200"
                type="button"
              >
                <p className="px-5 py-2 text-base">Categoria 2</p>
              </button>
            </Link>
            <Link href="/">
              <button
                className=" rounded-lg bg-white  text-black shadow-md shadow-white duration-300 hover:mx-2 hover:scale-110 hover:delay-200"
                type="button"
              >
                <p className="px-5 py-2 text-base">Categoria 3</p>
              </button>
            </Link>
            <Link href="/">
              <button
                className="rounded-lg bg-white text-black shadow-md shadow-white duration-300 hover:mx-2 hover:scale-110 hover:delay-200"
                type="button"
              >
                <p className="px-5 py-2 text-base">Categoria 4</p>
              </button>
            </Link>
          </nav>
        </header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} coli-js
        </footer>
      </body>
    </html>
  );
}
